version: '3'

services: 
  jsonbackend:
    build: ./fake-json-backend
    ports: 
    - 3355:3333

  grafana:
    image: grafana/grafana
    ports: 
    - 3000:3000
    volumes: 
    - grafana-storage:/var/lib/grafana
    - "./grafana/plugins/rapidminer-grafana-datasource:/var/lib/grafana/plugins/rapidminer-grafana-datasource"
    - "./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards"
    - "./grafana/dashboards:/var/lib/grafana/dashboards"
    - "./grafana/plugins/extended-graph-panel:/var/lib/grafana/plugins/extended-graph-panel"
    # environment: 
    # - GF_LOG_LEVEL=debug

  proxy:
    build: ./proxy
    ports:
    - 5000:5000
    restart: always
    environment: 
      - RAPIDMINER_SERVER_HOST=rapidminer-server
      - RAPIDMINER_SERVER_PORT=8080
    volumes: 
      - "./proxy/proxy.py:/code/proxy.py"

  database:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=rapid_server_db
      - POSTGRES_USER=rapid_server_db_user
      - POSTGRES_PASSWORD=rapid_server_db_pass
    volumes:
      - postgredbvol:/var/lib/postgresql/data

  python-datasource:
    build: ./python-datasource
    ports:
      - 6000:6000
    volumes:
      - "./python-datasource/python-datasource/datasource.py/:/code/python-datasource/datasource.py"
  
  mysql:
    image: mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=weather
      - MYSQL_USER=weatheruser
      - MYSQL_PASSWORD=userpass
    volumes: 
      - "./data/temperature_newyork_cleaned.csv:/var/lib/mysql-files/weather-data/temperature_newyork.csv"
      - "./mysql-backend/scripts/:/docker-entrypoint-initdb.d"
      - "./mysql-backend/config:/etc/mysql/conf.d"

  weather-api:
    build: ./weather-api
    ports: 
      - 7000:7000
    volumes: 
      - "./weather-api/weather_api.py:/code/weather_api.py"
      - "./data/historical/data_cleaned.csv:/weather-data/data.csv"

  rapidminer-server:
    image: rapidminer/rapidminer-server:9.3.0
    environment:
      - DBHOST=database
      - DBSCHEMA=rapid_server_db
      - DBUSER=rapid_server_db_user
      - DBPASS=rapid_server_db_pass
      - BROKER_ACTIVEMQ_USERNAME=some-amq-username
      - BROKER_ACTIVEMQ_PASSWORD=some-secure-amq-password
      - JOBSERVICE_AUTH_SECRET=c29tzs1hdxrolxnly3jldao=
    volumes:
      - servervol:/persistent-rapidminer-home
    ports:
      - 8080:8080
    depends_on:
      - database
    links:
      - database
      
  job-agent:
    image: rapidminer/rapidminer-execution-jobagent:9.3.0
    environment:
      - RAPIDMINER_SERVER_HOST=rapidminer-server
      - RAPIDMINER_SERVER_PORT=8080
      - RAPIDMINER_SERVER_PROTOCOL=http
      - JOBAGENT_QUEUE_ACTIVEMQ_URI=failover:(tcp://rapidminer-server:5672)
      - JOBAGENT_QUEUE_ACTIVEMQ_USERNAME=some-amq-username
      - JOBAGENT_QUEUE_ACTIVEMQ_PASSWORD=some-secure-amq-password
      - JOBAGENT_AUTH_SECRET=c29tzs1hdxrolxnly3jldao=
      - JOBAGENT_CONTAINER_COUNT=1
      - JOBAGENT_CONTAINER_MEMORYLIMIT=4096
      - JOB_QUEUE=DEFAULT
    links:
      - rapidminer-server
    depends_on:
      - rapidminer-server

volumes: 
  grafana-storage:
  postgredbvol:
  servervol:
