{
 "title": "Provisioned",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "city1", "query": "Vancouver" },
   { "name": "city2", "query": "New York" }
  ]
 },
 "panels": [
  {
   "title": "Python datasource (New York close to alltime records)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "weather-table", "type": "table" }
   ]
  },
  {
   "title": "Timeseries data from RM Webservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=$city1",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=$city2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dynamic bar chart RM Webservice (min)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=$city1",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=$city2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dynamic bar chart RM Webservice (max)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=$city1",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=$city2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dynamic bar chart RM Webserivce (count)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=Vancouver",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=New York",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dynamic bar chart RM Webservice (total)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=$city1",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=$city2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dynamic bar chart RM Webservice (avg)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "target": "weather_retrieve_process?city=$city1",
     "type": "timeserie"
    },
    {
     "target": "weather_retrieve_process?city=$city2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Table data from RM WebService",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "parameters": [
      { "key": "city", "value": "$city1" }
     ],
     "target": "weather_retrieve_process?city=$city1",
     "type": "table"
    }
   ]
  },
  {
   "title": "JSONbackend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "upper_25", "type": "timeserie" },
    { "target": "upper_50", "type": "timeserie" },
    { "target": "upper_75", "type": "timeserie" },
    { "target": "upper_90", "type": "timeserie" },
    { "target": "upper_95", "type": "timeserie" }
   ]
  },
  {
   "title": "Dynamic bar chart (JSONbackend)",
   "type": "graph-panel-template-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "upper_25", "type": "timeserie" },
    { "target": "upper_50", "type": "timeserie" },
    { "target": "upper_75", "type": "timeserie" },
    { "target": "upper_90", "type": "timeserie" },
    { "target": "upper_95", "type": "timeserie" }
   ]
  }
 ]
}